In [1]:
import numpy as np

## LEVEL 1: BASICS (Arrays, shape, dtype) — 1–15

In [3]:
# Create a NumPy array with numbers from 1 to 10.
num = np.arange(1,11)
num


(10,)

In [6]:
# Create a NumPy array of all zeros with shape (3, 4).
all_zero = np.array([[1,2,3,4],[5,6,7,8],[10,11,12,13]])
all_zero * 0
all_zero.shape

(3, 4)

In [8]:
all_zero = np.zeros((3,4))
all_zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.full((3,4),0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
# Create a NumPy array of all ones with shape (2, 5).
np.full((2,5),1)


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
# Create an array of even numbers between 10 and 50.
x = np.arange(10,52,2)
x

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [31]:
x = np.linspace(10,50,21)
x

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38., 40., 42., 44., 46., 48., 50.])

In [32]:
num = np.arange(10,51)
even = num[num % 2 == 0]
even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [33]:
# Find the shape and datatype of an array.
all_zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
all_zero.shape

(3, 4)

In [40]:
type(all_zero)

numpy.ndarray

In [56]:
all_zero.ndim

2

In [55]:
# Convert a Python list [1, 2, 3, 4] into a NumPy array.
arr = [1, 2, 3, 4]
np.array(arr,dtype=int)

array([1, 2, 3, 4])

In [70]:
# Create a 2D array with 3 rows and 3 columns filled with random integers.
arr = np.random.randint(1,10,(3,3))
arr

array([[9, 6, 6],
       [8, 5, 4],
       [5, 1, 4]], dtype=int32)

In [74]:
arr = np.arange(1,19).reshape((2,3,3))
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [76]:
arr = np.random.randint(1,10,(3,3))
arr

array([[8, 9, 8],
       [9, 3, 9],
       [7, 8, 5]], dtype=int32)

In [87]:
# Access the element at row 2, column 1 from a 2D array.
arr = np.arange(1,10).reshape((3,3))
acc = arr[1,0]
acc

np.int64(4)

In [88]:
# Change the value of a specific element in a NumPy array.
arr = np.arange(1,10).reshape((3,3))
arr[1,1] = 0
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
# Find the length of a NumPy array.
len(arr)

3

In [92]:
arr.shape

(3, 3)

In [93]:
arr.size

9

In [99]:
# Create an identity matrix of size 4
arr = np.identity(4,dtype=int)
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [106]:
arr = np.arange(1,10)
x = arr.sum()
x


np.int64(45)

In [110]:
# Create an array using arange(from 0 to 20 with step 2.
arr = np.arange(0,21,2)
arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [111]:
# Reshape a 1D array of size 12 into a 3×4 array.
arr = np.arange(1,13).reshape((3,4))
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [116]:
# Flatten a 2D array into 1D.
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [117]:
# Check if an array contains only numeric values.
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
x.dtype

dtype('int64')

In [121]:
x[3] == 'five'


False

In [132]:
x = np.array([ 1,  2,  3,  4,  5,  False,  7,  8,  9, 10, 11, 12])

In [133]:
x.dtype

dtype('int64')

In [134]:
type(x)

numpy.ndarray

## LEVEL 2: Indexing, slicing, boolean logic — 16–30


In [145]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
# Extract the first 5 elements from an array.
arr = np.arange(1,10)
arr[:5]

array([1, 2, 3, 4, 5])

In [149]:
# Extract the last 3 elements from an array.
arr[-3:]

array([7, 8, 9])

In [152]:
arr_2 = np.arange(1,10).reshape((3,3))
arr_2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [154]:
# Slice a 2D array to get the first two rows.
arr_2[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [155]:
# Slice a 2D array to get the last column.
arr_2[0:3,2]

array([3, 6, 9])

In [156]:
arr_2[:,-1]

array([3, 6, 9])

In [177]:
# Find all elements greater than 50 in an array.
arr_100 = np.random.randint(1,100,(10))
x = arr_100 > 50
arr_100[x]

array([79, 65, 57, 61, 51], dtype=int32)

In [178]:
arr_100

array([79, 65, 49, 57, 61, 51, 29, 50, 44,  5], dtype=int32)

In [194]:
z = np.where(
    arr_100 > 50
)
arr_100[z]


array([79, 65, 57, 61, 51], dtype=int32)

In [179]:
x = arr_100 > 50
arr_100[x]

array([79, 65, 57, 61, 51], dtype=int32)

In [180]:
for i in arr_100:
    if i > 50:
        print(i)

79
65
57
61
51


In [181]:
result = [i for i in arr_100 if i > 50]
result

[np.int32(79), np.int32(65), np.int32(57), np.int32(61), np.int32(51)]

In [182]:
# Replace all values greater than 100 with 100.
numgret100 = np.random.randint(50,150,(12))

In [183]:
numgret100

array([144, 100,  99, 124, 105, 123, 101, 107,  95,  77,  72,  77],
      dtype=int32)

In [190]:
x = np.where(
    numgret100 > 100 , 
    numgret100 ,
    100
)
x

array([144, 100, 100, 124, 105, 123, 101, 107, 100, 100, 100, 100],
      dtype=int32)

In [195]:
# Count how many values are less than 30.
count = np.random.randint(20,40,(10))


In [196]:
count

array([21, 32, 30, 20, 34, 22, 39, 23, 27, 36], dtype=int32)

In [199]:
x = np.where(count < 30)


1

In [200]:
x = len(count[count < 30])
x

5

In [201]:
x = np.sum(count < 30)
x

np.int64(5)

In [202]:
x = np.count_nonzero(count < 30)
x

5

In [203]:
# Find indices where values are even.
pos = np.random.randint(20,40,(10))


In [204]:
pos

array([28, 23, 23, 26, 21, 32, 38, 32, 23, 27], dtype=int32)

In [207]:
x = np.where(
    pos % 2 == 0
)
x

(array([0, 3, 5, 6, 7]),)

In [210]:
pos

array([28, 23, 23, 26, 21, 32, 38, 32, 23, 27], dtype=int32)

In [209]:
# Select elements divisible by 3.
pos
x = np.where(
    pos % 3 == 0 
)
pos[x]

array([21, 27], dtype=int32)

In [212]:
# Replace negative numbers with 0.
neg = np.random.randint(-20,20,(15))

In [213]:
neg

array([ -2,  13,  -1, -14, -15,   9, -12,   1,  13,  15, -17, -19,  -1,
       -12,  16], dtype=int32)

In [215]:
x = np.where(
    neg > 0,
    neg,
    0
)
x

array([ 0, 13,  0,  0,  0,  9,  0,  1, 13, 15,  0,  0,  0,  0, 16],
      dtype=int32)

In [216]:
# Reverse a NumPy array.
rev = np.random.randint(1,20,(15))


In [217]:
rev

array([ 5,  9, 14, 18, 15,  5, 13,  9,  2, 10, 16,  6, 17, 18,  1],
      dtype=int32)

In [234]:
x = np.sort(rev)

In [235]:
x[::-1]

array([18, 18, 17, 16, 15, 14, 13, 10,  9,  9,  6,  5,  5,  2,  1],
      dtype=int32)

In [236]:
# Sort an array in ascending order.
z = np.random.randint(1,20,(15))

In [237]:
z

array([17,  9, 18,  2,  4,  9, 18,  1, 13,  7, 17, 11, 14,  2, 12],
      dtype=int32)

In [238]:
np.sort(z)

array([ 1,  2,  2,  4,  7,  9,  9, 11, 12, 13, 14, 17, 17, 18, 18],
      dtype=int32)

In [239]:
# Sort an array in descending order.
z

array([17,  9, 18,  2,  4,  9, 18,  1, 13,  7, 17, 11, 14,  2, 12],
      dtype=int32)

In [242]:
x = np.sort(z)
x[::-1]

array([18, 18, 17, 17, 14, 13, 12, 11,  9,  9,  7,  4,  2,  2,  1],
      dtype=int32)

In [244]:
-np.sort(-z)

array([18, 18, 17, 17, 14, 13, 12, 11,  9,  9,  7,  4,  2,  2,  1],
      dtype=int32)

In [246]:
# Remove duplicates from an array.
x = np.random.randint(1,5,(10))

In [247]:
x

array([2, 4, 1, 2, 3, 1, 1, 4, 1, 3], dtype=int32)

In [250]:
y = np.unique(x)
y

array([1, 2, 3, 4], dtype=int32)

In [251]:
# Find unique values and their counts.
len(y)

4

## LEVEL 3: Math & statistics — 31–40





Compute the dot product of two arrays.

Calculate row-wise and column-wise sums of a 2D array.

Find the difference between consecutive elements.

In [264]:
# Find the sum of all elements in an array.
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [266]:
x.sum().astype(int)
x.mean().astype(int)

np.int64(5)

In [277]:
# Find the mean of an array.
x = np.random.randint(1,5,(10))

In [278]:
x

array([2, 1, 4, 4, 2, 2, 3, 2, 4, 1], dtype=int32)

In [279]:
np.mean(x).astype(int)

np.int64(2)

In [281]:
# Find the median of an array.
x = np.arange(1,10)
np.median(x).astype(int)

np.int64(5)

In [282]:
np.mean(x).astype(int)

np.int64(5)

In [287]:
# Find the standard deviation of an array.
x
std = np.std(x)
std

np.float64(2.581988897471611)

In [290]:
# Find the minimum and maximum value.
x = np.random.randint(1,10,(10))

In [291]:
x

array([2, 9, 6, 6, 9, 9, 7, 7, 2, 3], dtype=int32)

In [294]:
x.min().astype(int)

np.int64(2)

In [295]:
x.max()

np.int32(9)

In [299]:
# Normalize an array (scale values between 0 and 1)
min = x.min()
max = x.max()
min

np.int32(2)

In [300]:
max

np.int32(9)

In [302]:
nor = ( x - min ) / ( max - min )
nor

array([0.        , 1.        , 0.57142857, 0.57142857, 1.        ,
       1.        , 0.71428571, 0.71428571, 0.        , 0.14285714])

In [ ]:
# Find the cumulative sum of an array.
