# NUMPY

In [135]:
import numpy as np

In [136]:
a = np.array(42)
a

array(42)

In [137]:
type(a)

numpy.ndarray

In [138]:
a.ndim

0

In [139]:
a.shape

()

In [140]:
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [141]:
type(b)

numpy.ndarray

In [142]:
b.ndim

1

In [143]:
b.shape

(5,)

## DIFFRENCWE BETWEEN LIST & ARRAY

## 2D ARRAY

In [144]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
a.ndim

2

In [146]:
a.size


6

In [147]:
b = np.array([[1,2,3,],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [148]:
b.shape

(4, 3)

In [149]:
b.ndim

2

# 3D DIMENTION

In [150]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [151]:
a.ndim

3

In [152]:
a.shape

(2, 2, 2)

In [153]:
type(a)

numpy.ndarray

In [154]:
c  =np.array([[[1,2],[3,4],[5,6],[7,8],[9,10]],[[11,12],[13,14],[15,16],[17,18],[19,20]],[[21,22],[23,24],[25,26],[27,28],[29,30]]])
c

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]]])

In [155]:
c.shape

(3, 5, 2)

In [156]:
c.ndim

3

# 4 DIMENTION

In [157]:
a = np.array([[[[1,2,3,4,5]]]])
a

array([[[[1, 2, 3, 4, 5]]]])

In [158]:
a.ndim

4

In [159]:
a.shape

(1, 1, 1, 5)

# ELEMENT ACCESSING

In [160]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [161]:
a[6]

np.int64(7)

In [162]:
f = np.array([[1,2,3],[4,5,6],[7,8,9]])
f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [163]:
f[1,1]

np.int64(5)

In [164]:
f[2,2]

np.int64(9)

In [165]:
x = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
x

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [166]:
x[1,0,2]

np.int64(9)

In [167]:
x[-1,-2,-1]

np.int64(9)

# sLICING

# 1D

In [168]:
 d1 = np.array([1,2,3,4,5,6,7,8,9,10])
d1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [169]:
d1[3:6]

array([4, 5, 6])

In [170]:
d1[-4:0
]

array([], dtype=int64)

# 2D

In [171]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [172]:
y[1:2]

array([[4, 5, 6]])

In [173]:
y[2,1:3]

array([8, 9])

In [174]:
y[:2,1:6]

array([[2, 3],
       [5, 6]])

In [175]:
y[:2,1:3]

array([[2, 3],
       [5, 6]])

# #D

In [176]:
c  =np.array([[[1,2],[3,4],[5,6],[7,8],[9,10]],[[11,12],[13,14],[15,16],[17,18],[19,20]],[[21,22],[23,24],[25,26],[27,28],[29,30]]])
c

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]]])

In [177]:
x = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
x

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [178]:
# 8 , #9



In [179]:
x = np.arange(1,10).reshape((3,3))
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [180]:
x.ndim

2

In [181]:
x.shape

(3, 3)

In [182]:
len(x)

3

In [183]:
type(x)

numpy.ndarray

# max

In [184]:
x = np.arange(1,7).reshape((2,3))
x

array([[1, 2, 3],
       [4, 5, 6]])

In [185]:
x.max()

np.int64(6)

In [186]:
x.min()

np.int64(1)

# row BAse

In [187]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [188]:
x.max(axis=0)

array([4, 5, 6])

In [189]:
x.min(axis=0)

array([1, 2, 3])

# column base

In [190]:
x.min(axis=1)

array([1, 4])

In [191]:
x.max(axis=1)


array([3, 6])

# argmax

In [192]:
# it is the function that returns the index
a = np.arange(1,7).reshape((2,3))

In [193]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [194]:
a.argmax()

np.int64(5)

In [195]:
a.argmax(axis=0)

array([1, 1, 1])

In [196]:
a.argmax(axis=1)

array([2, 2])

# argmin

In [197]:
x.argmin(axis = 0)

array([0, 0, 0])

In [198]:
x.argmin(axis = 1)

array([0, 0])

In [199]:
z = np.arange(1,7).reshape((2,3))
z

array([[1, 2, 3],
       [4, 5, 6]])

In [200]:
z.reshape((1,6))

array([[1, 2, 3, 4, 5, 6]])

In [201]:
z.reshape(1,2,3)

array([[[1, 2, 3],
        [4, 5, 6]]])

In [202]:
z.reshape(3,2,1)

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [203]:
z.reshape(2,1,3)

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [204]:
y = np.arange(1,13).reshape((2,2,3))
y

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [205]:
y.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [206]:
# zero matrix

In [207]:
x = np.zeros((2,2,3),dtype=int)
x

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [208]:
x = np.zeros([2,2,3],dtype=int)
x

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [209]:
y = np.ones([2,2,3],dtype=int)
y

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [210]:
t = np.ones([3,2,2],dtype=int)

In [211]:
t

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

# diagonal matrix

In [212]:
x = np.arange(1,10).reshape(3,3)

In [213]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [214]:
a = np.diag([9,9,9])
a

array([[9, 0, 0],
       [0, 9, 0],
       [0, 0, 9]])

In [215]:
a

array([[9, 0, 0],
       [0, 9, 0],
       [0, 0, 9]])

# identical matrix

In [216]:
x =  np.eye(4,dtype=int)
x

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [217]:
y = np.eye(3,4,dtype=int)
y

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [218]:
y = np.eye(3,4,k=2,dtype=int)
y

array([[0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0]])

In [219]:
x = np.eye(4,3,k=-1,dtype=int)
x

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [220]:
x = np.full((3,6),3)
x

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [221]:
x = np.random.random((2,3))
x

array([[0.19880455, 0.7931358 , 0.17454957],
       [0.91807426, 0.59428997, 0.08699157]])

In [224]:
x = np.arange(1,10,).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [225]:
x[:2,1:3]

array([[2, 3],
       [5, 6]])

In [227]:
y = np.arange(1,13).reshape(2,2,3)
y

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [231]:
#  return 8,9
y [1,0,1:3]


array([8, 9])

In [232]:
# return 2,3,5,6
y[0,:2,1:3]

array([[2, 3],
       [5, 6]])

In [233]:
# return 4,5
y[0,1,0:2]

array([4, 5])